type AppColors = {
  primary: string;
  darkText: string;
  lightText: string;
  white: string;
  background: string;
  stroke: string;
  error: string;
  success: string;
  border: string;
  inActiveDot: string;
  gradientBtn: string;
  textInput: string;
  modal: string;
  lightGreen: string;
  lightRed: string;
  lightOrange: string;
  boxBg: string;
  black: string;
  verticalLine: string;
  delete: string;
  serviceBG: string;
  rating: string;
  ratingBg: string;
  line: string;
  disable: string;
  cardBG: string;
  borderColor: string;
  checkOut: string;
  packageBg: string;
  packageBg1: string;
  packageBg2: string;
  pending: string;
  accepted: string;
  status: string;
  divider: string;
  selectedPlan: string;
  gradientColor: string;
  selectedCategory: string;
  assigned: string;
  hold: string;
  darkTheme: string;
  darkBg: string;
  darkBorder: string;
  darkCardBg: string;
  darkSubText: string;
  darkCard: string;
  dividerColor: string;
};

const appColors: AppColors = {
  primary: '#FE782E',
  darkText: '#171B27',
  lightText: '#647683',
  white: '#FFFFFF',
  background: '#F4FBFF',
  stroke: '#E0F3FE',
  error: '#FF4242',
  success: '#0CBC8B',
  border: '#ECEDEE',
  inActiveDot: '#D3D9DF',
  gradientBtn: '#FF9E69',
  textInput: '#F7F8F8',
  modal: 'rgba(0, 0, 0, 0.5)',
  lightGreen: '#E7F8F3',
  lightRed: '#FFECEC',
  lightOrange: '#FAE7DB',
  boxBg: '#F9FAFA',
  black: '#000000',
  verticalLine: '#D6D6D6',
  delete: '#F8E6E6',
  serviceBG: '#FFF1EA',
  rating: '#FFE5D7',
  ratingBg: '#FFF1EA',
  line: '#FF9898',
  disable: '#D8DDE0',
  cardBG: '#E8EAEC',
  borderColor: '#D8DBDE',
  checkOut: '#FFF7F2',
  packageBg: '#5C6AE9',
  packageBg1: '#A76854',
  packageBg2: '#CED1AF',
  pending: '#FFB015',
  accepted: '#397DFF',
  status: '#FAD5D5',
  divider: '#FFD9C4',
  selectedPlan: '#FFF2EA',
  gradientColor: 'rgba(254, 120, 46, 0.5)',
  selectedCategory: '#FFF2EB',
  assigned: '#48BFFD',
  hold: '#FE2E92',
  darkTheme: '#1A1C28',
  darkBg: '#F1F1F1',
  darkBorder: '#454851',
  darkCardBg: '#262935',
  darkSubText: '#808B97',
  darkCard: '#262935',
  dividerColor: '#FFDBDB',
};

export default appColors;
